### ISSUE TITLE
No module named 'PyKDL'

### ISSUE THREAD

**Issue by cublicma** [uwgraphics/relaxed_ik_ros2#3]
I followed the instructions to install RangeIK (relaxed_ik_ros2) on my WSL2. I can go over all steps till the verification step. 
When I run:

> ros2 launch relaxed_ik_ros2 demo.launch.py

Tthe error popped up:

> [rviz2-2] QStandardPaths: wrong permissions on runtime directory /run/user/1000/, 0755 instead of 0700
[rviz_viewer.py-4] Traceback (most recent call last):
[rviz_viewer.py-4]   File "/home/ma/ros2_ws/install/relaxed_ik_ros2/lib/relaxed_ik_ros2/rviz_viewer.py", line 19, in <module>
[rviz_viewer.py-4]     from robot import Robot
[rviz_viewer.py-4]   File "/home/ma/ros2_ws/src/relaxed_ik_ros2/scripts/robot.py", line 14, in <module>
[relaxed_ik_rust.py-1] Traceback (most recent call last):
[relaxed_ik_rust.py-1]   File "/home/ma/ros2_ws/install/relaxed_ik_ros2/lib/relaxed_ik_ros2/relaxed_ik_rust.py", line 19, in <module>
[relaxed_ik_rust.py-1]     from kdl_parser import kdl_tree_from_urdf_model
[relaxed_ik_rust.py-1]   File "/home/ma/ros2_ws/src/relaxed_ik_ros2/scripts/kdl_parser.py", line 35, in <module>
[relaxed_ik_rust.py-1]     import PyKDL as kdl
[rviz_viewer.py-4]     import PyKDL
[rviz_viewer.py-4] ModuleNotFoundError: No module named 'PyKDL'
[relaxed_ik_rust.py-1] ModuleNotFoundError: No module named 'PyKDL'
[ERROR] [relaxed_ik_rust.py-1]: process has died [pid 17493, exit code 1, cmd '/home/ma/ros2_ws/install/relaxed_ik_ros2/lib/relaxed_ik_ros2/relaxed_ik_rust.py --ros-args -r __node:=relaxed_ik_rust -r __ns:=/ --params-file /tmp/launch_params_x40xppxs'].

I am using Ubuntu 22.04, ROS 2 Humble, Rustc V1.81.0. I tried with Rustc V1.58.1 but some packages require a higher version.

**Comment by jjpatino-byte** [comment]
Were you able to solve this error? @cublicma
